name: Set branch info
timeout-minutes: 1
runs-on: ubuntu-latest
steps:
  - name: Set branch name envvar
    run: |
      echo "::set-env name=BRANCH_NAME::${GITHUB_REF#refs/heads/}"
  - name: Set branch issue envvar
    run: |
      issue="${BRANCH_NAME##*-}"
      [[ "${issue}" =~ '^[0-9]+$' ]] || >&2 echo "issue num not parsed"; exit 1
      echo "::set-env name=BRANCH_ISSUE::${issue}"
