name: Set branch info
shell: bash
run: |
  name="${GITHUB_REF#refs/heads/}"
  issue="${name##*-}"
  [[ "${issue}" =~ '^[0-9]+$' ]] || >&2 echo "issue num not parsed"; exit 1
  echo "##[set-output name=name;]${name}"   # $\{ steps.branch-info.outputs.name }}
  echo "##[set-output name=issue;]${issue}" # $\{ steps.branch-info.outputs.issue }}
id: branch-info
