name: Set branch info
shell: bash
run: |
  name="${GITHUB_REF#refs/heads/}"
  issue="${name##*-}"
  [[ "${issue}" =~ '^[0-9]+$' ]] || >&2 echo "issue num not parsed"; exit 1
  echo "::set-env name=BRANCH_NAME::${name}"
  echo "::set-env name=BRANCH_ISSUE::${issue}"
