name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set continuation envvar
        run: |
          echo "::set-env name=CALL_SUBSEQUENT::true"
      - name: Set branch name envvar
        run: |
          echo "::set-env name=BRANCH_NAME::${GITHUB_REF#refs/heads/}"
      - name: Set branch issue envvar
        run: |
          issue="${BRANCH_NAME##*-}"
          ! [[ "${issue}" =~ ^[0-9]+$ ]] && echo "::set-env name=CALL_SUBSEQUENT::false"
          echo "::set-env name=BRANCH_ISSUE::${issue}"
      - name: Halt if PR for branch exists AND most recent commit is not NOWIP
        if: env.CALL_SUBSEQUENT
        run: |
          echo "TEST"
