name: A workflow for my Hello World file
on:
  push:
    branches:
      - '*/*-[0-9]+'
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set continuation envvar
        run: |
          echo "::set-env name=CALL_SUBSEQUENT::false"
      - name: Set branch name envvar
        run: |
          echo "::set-env name=BRANCH_NAME::${GITHUB_REF#refs/heads/}"
      - name: Set branch issue envvar
        run: |
          issue="${BRANCH_NAME##*-}"
          ! [[ "${issue}" =~ ^[0-9]+$ ]] || echo "::set-env name=CALL_SUBSEQUENT::false"
          echo "::set-env name=BRANCH_ISSUE::${issue}"
      - name: Halt if PR for branch exists AND most recent commit is not NOWIP
        if: env.CALL_SUBSEQUENT == true
        run: |
          echo "TEST"
      - name: Create pull request
        run: |
          set -e
          hub issue
          infoFile="commits_info"
          git log \
            --left-right \
            --graph \
            --cherry-pick \
            --oneline \
            --pretty=format:%s \
            origin/master..origin/"${BRANCH_NAME}" >> "${infoFile}"
          echo >> "${infoFile}" # add missing newline
          tac "${infoFile}" > "rev_${infoFile}" && mv "rev_${infoFile}" "${infoFile}" # reverse data
          wipLine="$(cat "${infoFile}" | grep "^> WIP" -n | head -n 1 | cut -d : -f1)"
          if 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/hello
        with:
          MY_NAME: "Mona"
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          BRANCH_ISSUE: ${{ env.BRANCH_ISSUE }}
