name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set branch name envvar
        run: |
          echo "::set-env name=BRANCH_NAME::${GITHUB_REF#refs/heads/}"
      - name: Set branch issue envvar
        run: |
          issue="${BRANCH_NAME##*-}"
          ! [[ "${issue}" =~ ^[0-9]+$ ]] && >&2 echo "issue num not parsed" && exit 1
          echo "::set-env name=BRANCH_ISSUE::${issue}"
      - name: Create pull request
        run: |
          hub clone "${GITHUB_REPOSITORY}"
          cd "${GITHUB_REPOSITORY#*/}"
          ls -la
      - uses: ./.github/actions/hello
        with:
          MY_NAME: "Mona"
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
          BRANCH_ISSUE: ${{ env.BRANCH_ISSUE }}
